### ISSUE TITLE
God-mode should be protected by Player.Immunity

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/modular-vc-mp-server#22]
In on of the scripts (I don't remember which one) we enable god-mode. We should also set Player.Immunity to 0x7F so that players are protected as good as possible.

It's not really an issue, but I believe I'v seen peoples health flicker in the past (as god-mode runs server-side).

**Comment by dracc** [comment]
https://github.com/JayFoxRox/modular-vc-mp-server/blob/80aaf31e30d19f03c7cc90de09dd638212e58963/scripts/module/stunting.nut#L149

**Comment by JayFoxRox** [comment]
Interesting - I assume there's no bit to protect from water damage for example :(

Closed (already implemented).
