### ISSUE TITLE
Ramp from ramp.nut is transparent

### ISSUE THREAD

**Issue by JayFoxRox** [JayFoxRox/modular-vc-mp-server#35]
Somehow it only has 220 alpha. This is a bug. It should be fully opaque.

(Maybe we can show player ramps as opaque, but other players ramps as transparent?)

**Comment by dracc** [comment]
How did you find this? Per player opacity is probably not implemented in vc:mp currently - we'd have to add support on our own somehow.

**Comment by JayFoxRox** [comment]
> Per player opacity is probably not implemented in vc:mp currently

You can set a World and a Secondary World for the player. So we'd need 2 ramp objects. 1 for the world everyone is in, and another one for the players unique world; however, this might cause minor collisions issues because of overlapping objects.

Alternatively, we could also create 100 ramps, each in each players unique world (but I assume this causes lots of network traffic + it's more complicated code).

**Comment by dracc** [comment]
We have playtested double ramps, last tested opacity value for the "public" ramp was 177. Worked good afaict. Will push a PR tomorrow morning.

**Comment by JayFoxRox** [comment]
128 was already okay. 200 was too opaque. I don't remember 177, but it feels too close to 200? I'd probably pick 150 or 160, so you can easily make out your own ramps.

**Comment by dracc** [comment]
177 was the last value we played with yesterday, was acceptable IMO.
